#ifndef ROOT_DIRECTORY_H
#define ROOT_DIRECTORY_H

/// This is a configuration file generated by CMake.
/// It contains the absolute path to the project's directory.
const char* logl_root = "/mnt/c/Users/haustintexas/OneDrive/Desktop/everything/GLSL/LearnOpenGL-master";

#endif
